/*
use crate::syscall_list::SyscallAbi::Common;
use crate::syscall_list::SyscallAbi::Only64;
use crate::syscall_list::SyscallAbi::OnlyX32;

#[derive(Copy, Clone)]
#[repr(u8)]
pub enum SyscallAbi {
    Common,
    Only64,
    OnlyX32,
}

#[repr(C)]
pub struct Syscall {
    id: usize,
    abi: SyscallAbi,
    name: &'static str,
    entry_point: &'static str,
}

impl Syscall {

    #[inline]
    pub fn id(&self) -> usize {
        self.id
    }

    #[inline]
    pub fn abi(&self) -> SyscallAbi {
        self.abi
    }

    #[inline]
    pub fn name(&self) -> &'static str {
        self.name
    }

    #[inline]
    pub fn entry_point(&self) -> &'static str {
        self.entry_point
    }

}

macro_rules! syscalls {
    ( $( $var_name: ident, $id: expr, $abi: expr, $name: expr, $entry: expr )* ) => {
        {
            $(
            static $var_name: Syscall = Syscall {
                id: $id,
                abi: $abi,
                name: $name,
                entry_point: $entry,
            };
            )*
        }
    };
}

// https://elixir.free-electrons.com/linux/v5.14/source/arch/x86/entry/syscalls/syscall_64.tbl

syscalls!(
    READ, 0, Common, "read", ""
    WRITE, 1, Common, "write", ""
    OPEN, 2, Common, "open", ""
    CLOSE, 3, Common, "close", ""
    STAT, 4, Common, "stat", ""
    FSTAT, 5, Common, "read", ""
    LSTAT, 6, Common, "read", ""
    POLL, 7, Common, "read", ""
    LSEEK, 8, Common, "read", ""
    MMAP, 9, Common, "read", ""
    MPROTECT, 10, Common, "read", ""
    MUNMAP, 11, Common, "read", ""
    BRK, 12, Common, "read", ""
    RT_SIGACTION, 13, Only64, "read", ""
    RT_SIGPROCMASK, 14, Common, "read", ""
    RT_SIGRETURN, 15, Only64, "read", ""
    IOCTL, 16, Only64, "read", ""
    PREAD64, 17, Common, "read", ""
    PWRITE64, 18, Common, "read", ""
    READV, 19, Only64, "read", ""
    WRITEV, 20, Only64, "read", ""
    ACCESS, 21, Common, "read", ""
    PIPE, 22, Common, "read", ""
    SELECT, 23, Common, "read", ""
    SCHED_YIELD, 24, Common, "read", ""
    MREMAP, 25, Common, "read", ""
    MSYNC, 26, Common, "read", ""
    MINCORE, 27, Common, "read", ""
    MADVISE, 28, Common, "read", ""
    SHMGET, 29, Common, "read", ""
    SHMAT, 30, Common, "read", ""
    SHMCTL, 31, Common, "read", ""
    DUP, 32, Common, "read", ""
    DUP2, 33, Common, "read", ""
    PAUSE, 34, Common, "read", ""
    NANOSLEEP, 35, Common, "read", ""
    GETITIMER, 36, Common, "read", ""
    ALARM, 37, Common, "read", ""
    SETITIMER, 38, Common, "read", ""
    GETPID, 0, Common, "read", ""
    SENDFILE, 0, Common, "read", ""
    SOCKET, 0, Common, "read", ""
    CONNECT, 0, Common, "read", ""
    ACCEPT, 0, Common, "read", ""
    SENDTO, 0, Common, "read", ""
    RECVFROM, 0, Only64, "read", ""
    SENDMSG, 0, Only64, "read", ""
    RECVMSG, 0, Only64, "read", ""
    SHUTDOWN, 0, Common, "read", ""
    BIND, 0, Common, "read", ""
    LISTEN, 0, Common, "read", ""
    GETSOCKNAME, 0, Common, "read", ""
    GETPEERNAME, 0, Common, "read", ""
    SOCKETPAIR, 0, Common, "read", ""
    SETSOCKOPT, 0, Only64, "read", ""
    GETSOCKOPT, 0, Only64, "read", ""
    CLONE, 0, Common, "read", ""
    FORK, 0, Common, "read", ""
    VFORK, 0, Common, "read", ""
    EXECVE, 0, Only64, "read", ""
    EXIT, 0, Common, "read", ""
    WAIT4, 0, Common, "read", ""
    KILL, 0, Common, "read", ""
    UNAME, 0, Common, "read", ""
    SEMGET, 0, Common, "read", ""
    SEMOP, 0, Common, "read", ""
    SEMCTL, 0, Common, "read", ""
    SHMDT, 0, Common, "read", ""
    MSGGET, 0, Common, "read", ""
    MSGSND, 0, Common, "read", ""
    MSGRCV, 0, Common, "read", ""
    MSGCTL, 0, Common, "read", ""
    FCNTL, 0, Common, "read", ""
    FLOCK, 0, Common, "read", ""
    FSYNC, 0, Common, "read", ""
    FDATASYNC, 0, Common, "read", ""
    TRUNCATE, 0, Common, "read", ""
    FTRUNCATE, 0, Common, "read", ""
    GETDENTS, 0, Common, "read", ""
    GETCWD, 0, Common, "read", ""
    CHDIR, 0, Common, "read", ""
    FCHDIR, 0, Common, "read", ""
    RENAME, 0, Common, "read", ""
    MKDIR, 0, Common, "read", ""
    RMDIR, 0, Common, "read", ""
    CREAT, 0, Common, "read", ""
    LINK, 0, Common, "read", ""
    UNLINK, 0, Common, "read", ""
    SYMLINK, 0, Common, "read", ""
    READLINK, 0, Common, "read", ""
    CHMOD, 0, Common, "read", ""
    FCHMOD, 0, Common, "read", ""
    CHOWN, 0, Common, "read", ""
    FCHOWN, 0, Common, "read", ""
    LCHOWN, 0, Common, "read", ""
    UNMASK, 0, Common, "read", ""
    GETTIMEOFDAY, 0, Common, "read", ""
    GETRLIMIT, 0, Common, "read", ""
    GETRUSAGE, 0, Common, "read", ""
    SYSINFO, 0, Common, "read", ""
    TIMES, 0, Common, "read", ""
    PTRACE, 0, Only64, "read", ""
    GETUID, 0, Common, "read", ""
    SYSLOG, 0, Common, "read", ""
    GETGID, 0, Common, "read", ""
    SETUID, 0, Common, "read", ""
    SETGID, 0, Common, "read", ""
    GETEUID, 0, Common, "read", ""
    GETEGID, 0, Common, "read", ""
    SETPGID, 0, Common, "read", ""
    GETPPID, 0, Common, "read", ""
    GETPGRP, 0, Common, "read", ""
    SETSID, 0, Common, "read", ""
    SETREUID, 0, Common, "read", ""
    SETREGID, 0, Common, "read", ""
    GETGROUPS, 0, Common, "read", ""
    SETGROUPS, 0, Common, "read", ""
    SETRESUID, 0, Common, "read", ""
    GETRESUID, 0, Common, "read", ""
    SETRESGID, 0, Common, "read", ""
    GETRESGID, 0, Common, "read", ""
    GETPGID, 0, Common, "read", ""
    SETFSUID, 0, Common, "read", ""
    SETFSGID, 0, Common, "read", ""
    GETSID, 0, Common, "read", ""
    CAPGET, 0, Common, "read", ""
    CAPSET, 0, Common, "read", ""
    RT_SIGPENDING, 0, Only64, "read", ""
    RT_SIGTIMEDWAIT, 0, Only64, "read", ""
    RT_SIGQUEUEINFO, 0, Only64, "read", ""
    RT_SIGSUSPEND, 0, Common, "read", ""
    SIGALTSTACK, 0, Only64, "read", ""
    UTIME, 0, Common, "read", ""
    MKNOD, 0, Common, "read", ""
    USELIB, 0, Only64, "read", ""
    PERSONALITY, 0, Common, "read", ""
    USTAT, 0, Common, "read", ""
    STATFS, 0, Common, "read", ""
    FSTATFS, 0, Common, "read", ""
    SYSFS, 0, Common, "read", ""
    GETPRIORITY, 0, Common, "read", ""
    SETPRIORITY, 0, Common, "read", ""
    SCHED_SETPARAM, 0, Common, "read", ""
    SCHED_GETPARAM, 0, Common, "read", ""
    SCHED_SETSCHEDULER, 0, Common, "read", ""
    SCHED_GETSCHEDULER, 0, Common, "read", ""
    SCHED_GET_PRIORITY_MAX, 0, Common, "read", ""
    SCHED_GET_PRIORITY_MIN, 0, Common, "read", ""
    SCHED_RR_GET_INTERVAL, 0, Common, "read", ""
    MLOCK, 0, Common, "read", ""
    MUNLOCK, 0, Common, "read", ""
    MLOCKALL, 0, Common, "read", ""
    MUNLOCKALL, 0, Common, "read", ""
    VHANGUP, 0, Common, "read", ""
    MODIFY_LDT, 0, Common, "read", ""
    PIVOT_ROOT, 0, Common, "read", ""
    _SYSCTL, 0, Only64, "read", ""
    PRCTL, 0, Common, "read", ""
    ARCH_PRCTL, 0, Common, "read", ""
    ADJTIMEX, 0, Common, "read", ""
    SETRLIMIT, 0, Common, "read", ""
    CHROOT, 0, Common, "read", ""
    SYNC, 0, Common, "read", ""
    ACCT, 0, Common, "read", ""
    SETTIMEOFDAY, 0, Common, "read", ""
    MOUNT, 0, Common, "read", ""
    UMOUNT2, 0, Common, "read", ""
    SWAPON, 0, Common, "read", ""
    SWAPOFF, 0, Common, "read", ""
    REBOOT, 0, Common, "read", ""
    SETHOSTNAME, 0, Common, "read", ""
    SETDOMAINNAME, 0, Common, "read", ""
    IOPL, 0, Common, "read", ""
    IOPERM, 0, Common, "read", ""
    CREATE_MODULE, 0, Only64, "read", ""
    INIT_MODULE, 0, Common, "read", ""
    DELETE_MODULE, 0, Common, "read", ""
    GET_KERNEL_SYMS, 0, Only64, "read", ""
    QUERY_MODULE, 0, Only64, "read", ""
    QUOTACTL, 0, Common, "read", ""
    NFSSERVCTL, 0, Only64, "read", ""
    GETPMSG, 0, Common, "read", ""
    PUTPMSG, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""
    READ, 0, Common, "read", ""

);
*/